CREATE TABLE usuarios(
id BIGINT NOT NULL AUTO_INCREMENT,
login VARCHAR(100) NOT NULL,
senha VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE topicos(
id BIGINT NOT NULL AUTO_INCREMENT,
titulo VARCHAR(255) NOT NULL,
mensagem TEXT NOT NULL,
data_criacao DATETIME,
status VARCHAR(100),
autor VARCHAR(255),
curso VARCHAR(255),
PRIMARY KEY(id)
);